### ISSUE TITLE
pair8.T does not match refsol2

### ISSUE THREAD

**Issue by jbrown215** [yuex/312-assn2-testsuite#1]
full output from refsol:
```
->eval (fn (g : <NONE :: nat, SOME :: nat, ALL :: nat>)
  g.ALL
=> )(<NONE = z, SOME = s(z)>);
Statics: term has type Nat
Malformed error in dynamics
```

The test harness expects a typefail.

It is not clear to me if this is a bug in the refsol, or a bug in the test case.

**Comment by yuex** [comment]
See piazza @164, Jan confirmed it if I didn't get him wrong.

**Comment by jbrown215** [comment]
speaking to @jez to see if we can clarify expectations. Without a working refsol it seems difficult to know what exactly we're supposed to be implementing. 

If Jan is indeed correct, then they gave us a very buggy implementation of Typ.aequiv

**Comment by yuex** [comment]
It seems the hidden test suite is not extremely extensive. Usually, the reference solution comes from one TA's history submission.

I think Typ.aequiv is correct according to alpha-equivalence's definition. The problem is that we have different semantics in LabT.

**Comment by jbrown215** [comment]
Yes, I agree with you that Typ.aequiv is correct for some definition of aequiv, just not the one for LabT :)

**Comment by jbrown215** [comment]
btw, turns out order does matter (@216), which is going to break a lot of these test cases

**Comment by yuex** [comment]
I wish they have just said so in the first place. That would save me a good Saturday...

**Comment by jbrown215** [comment]
youre still the real MVP! great job on this!

**Comment by jbrown215** [comment]
also, @216 doesnt clarify this. the comment on @169 will, though
